---
- name: Configure invetory groups
  hosts: all
  
  roles:
  - { role: ocp-terraform-pre, when: invetory_provider == "terraform" }

- hosts: all
  roles:
   - subscription
   - ocp-pre-hooks

- hosts: masters
  roles:
   - ocp-pre-hooks-masters
